@rootURL = http://localhost:5112

GET {{rootURL}}/weatherforecast/
Accept: application/json

### //This is used as a separator between requests

GET {{rootURL}}/api/books //We set here out URL, Then we specify the format we want the response to be in which is JSON
Accept: application/json 

###//This is used as a separator between requests

GET {{rootURL}}/api/books/2 //We set here out URL, Then we specify the format we want the response to be in which is JSON
Accept: application/json